name: Sleep Action
author: juliangruber
description: 'Sleep for a set period of time'
branding:
  icon: 'tool'
  color: purple
inputs:
  time:
    description: 'A time period as ms or string (100, 10s, 1m)'
runs:
  using: 'node16'
  main: 'dist/index.js'
